
project = 'drawer-task-demo'

model_folder = ''

nesting = 1
video_extension = 'MOV'

[filter]
enabled = true
type = 'viterbi'
score_threshold = 0.8 # score below which to count as bad
spline = true # interpolate using cubic spline instead of linear

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid
board_size = [10, 7]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 18.75 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 25 # mm

animal_calibration = false

fisheye = true

display_calibration_result = true

[labeling]
scheme = [
   ["Index-nail", "Index-DIP", "Index-PIP"]
 ]

[triangulation]
triangulate = true
cam_regex = '-cam([A-Z])'
cam_align = "A"
ransac = true
optim = false
constraints = [
   ["Index-nail", "Index-DIP"], ["Index-DIP", "Index-PIP"]
]
scale_smooth = 2
scale_length = 2
reproj_error_threshold = 3
score_threshold = 0.6
n_deriv_smooth = 2

