
project = 'hand-demo'

model_folder = 'C:\Users\903337.DESKTOP-KA9V2TP\Desktop\anipose_development\hand-demo-dlc-TuthillLab-2019-08-05'

nesting = 1
video_extension = 'MOV'

[filter]
enabled = true
type = 'viterbi'
score_threshold = 0.8 # score below which to count as bad
spline = true # interpolate using cubic spline instead of linear

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid
board_size = [10, 7]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 18.75 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 25 # mm

animal_calibration = false

fisheye = true

[labeling]
scheme = [
   ["base", "MCP1", "PIP1", "tip1"],
   ["base", "MCP2", "PIP2", "DIP2", "tip2"],
   ["base", "MCP3", "PIP3", "DIP3", "tip3"],
   ["base", "MCP4", "PIP4", "DIP4", "tip4"],
   ["base", "MCP5", "PIP5", "DIP5", "tip5"]
 ]

[triangulation]
triangulate = true
cam_regex = '-cam([A-Z])'
cam_align = "A"
ransac = true
optim = true
constraints = [
   ["base", "MCP1"], ["MCP1", "PIP1"], ["PIP1", "tip1"],
   ["base", "MCP2"], ["MCP2", "PIP2"], ["PIP2", "DIP2"], ["DIP2", "tip2"],
   ["base", "MCP3"], ["MCP3", "PIP3"], ["PIP3", "DIP3"], ["DIP3", "tip3"],
   ["base", "MCP4"], ["MCP4", "PIP4"], ["PIP4", "DIP4"], ["DIP4", "tip4"],
   ["base", "MCP5"], ["MCP5", "PIP5"], ["PIP5", "DIP5"], ["DIP5", "tip5"]
]
scale_smooth = 2
scale_length = 2
reproj_error_threshold = 3
score_threshold = 0.6
n_deriv_smooth = 2

